version: '3'

services:
    laravel-app:
        image: php:7.4-apache
        container_name: laravel-app
        ports:
            - "81:80"
        volumes:
            - /home/ubuntu/omg_laravel
        depends_on:
            - mysql-db

    mysql-db:
        image: mysql:latest
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "82:80"
        environment:
            PMA_HOST: mysql-db
